query GetProductThemes{
  productThemes {
    data {
      id
      attributes {
        title
        description
        slug
        theme {
          mainColor
          darkenColor
          lightenColor
        }
      }
    }
  }
}